### PR TITLE
changed type to Int64 to read BIGINT from SQL DB

### PR DESCRIPTION
**Pull request by kafisatz**
On my system Culong and Clong are (U)Int32. I needed the following changes to make things work. Can you please take a look?

### CODE REVIEW

**Comment by nkottary** [comment]
Is the change `client_flag::Culong` to `client_flag::Unsigned` necessary for this fix ?

**Comment by kafisatz** [comment]
On my system culong is UInt32.
I get an error when connecting if I do not change this:

julia> con = mysql_connect(hostName, userName, password, db)
ERROR: MethodError: `mysql_connect` has no method matching mysql_connect(::ASCII
String, ::ASCIIString, ::ASCIIString, ::ASCIIString, ::UInt32, ::Ptr{Int8}, **::UInt64**)
Closest candidates are:
  mysql_connect(::AbstractString, ::AbstractString, ::AbstractString, ::AbstractString, ::UInt32, ::Ptr{Int8}, **::UInt32**)
  mysql_connect(::AbstractString, ::AbstractString, ::AbstractString, ::AbstractString)
 in mysql_connect at C:\Users\workstation\.julia\MySQL\src\handy.jl:44

**Comment by nkottary** [comment]
Hi sorry for the late reply. Take a look at his diff 

[mysql.txt](https://github.com/JuliaDB/MySQL.jl/files/17416/mysql.txt)

I think its better to use UInt32 instead of either of Culong or Unsigned. Also none of the client_flag options need more that 32 bits, so this should work.

Can you make the above changes, test and commit. I will merge this after that. Thanks.

**Comment by kafisatz** [comment]
Hi I made some amendments. Like this, things work fine for me. Please have a look.
I have not worked with git diff before. I hope I included everything you suggested.

**Pull request merged**
